### ISSUE TITLE
Markings Port

### ISSUE THREAD

**Issue by vulppine** [vulppine/fox-station-14#7]
Port all the markings from SS13 into SS14.

This is an issue because this takes a while. PRs are appreciated to help with the marking port.

This may be useful: https://github.com/space-wizards/RSI.py

**Comment by vulppine** [comment]
Here's a prototype format reference for anybody who's interested (this is using the multi-color marking prototype, so any markings PR'd will not be merged until that is merged):
``` yaml
- type: anthroMarking
  id: MarkingId
  bodyPart: Chest
  markingLayerNames: [ LayerName1, LayerName2 ] 
  sprites:
  - sprite: Path/To/Sprite
    state: Layer1
  - sprite: Path/To/Sprite
    state: Layer2
```

The number of sprites **must** match the number of layer names, otherwise it will not be a valid marking.

Sprites should be stored in `Resources/Textures/AnthroSystem/Mobs/Customization/Markings`

The list of valid body parts to mask over are:
- Chest
- Head
- RArm
- LArm
- RHand
- LHand
- RLeg
- LLeg
- RFoot
- LFoot
